spring:
  application:
    name: contact-report
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        default_schema: db2admin
        show:
          sql: true
        dialect: org.hibernate.dialect.DB2Dialect
    show-sql: true
  datasource:
    url: jdbc:db2://M2UDB102:50000/MFP_QA
    username: udb_batchdev004
    password: BNMghjTYUd004
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



logging:
  level:
    root: INFO

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /manage
      exposure.include: mappings,health
    mappings:
      enabled: true

app:
  name: Contact Report
  profile: qa
  