SELECT  DLR_CD, 
		DBA_NM, 
		STATUS_CD, 
		STATUS_DT, 
		RGN_CD, 
		CITY_NM, 
		ZIP1_CD, 
		CNTY_CD, 
		ST_CD, 
		MDA_CD, 
		TIME_ZONE_CD, 
		MDA_NM, 
		ZONE_CD, 
		DISTRICT_CD, 
		FACILITY_TYPE, 
		RGN_NM, 
		W_UPDT_DT
FROM $SCHEMA$DEALERS
;
DROP INDEX IF EXISTS $SCHEMA$IX_DEALERS
;
CREATE INDEX $SCHEMA$IX_DEALERS ON $SCHEMA$DEALERS(DLR_CD)
;
CREATE INDEX $SCHEMA$IX_DEALER_LOCATIONS ON $SCHEMA$DEALERS(RGN_CD, ZONE_CD, DISTRICT_CD, DLR_CD)
