DROP VIEW IF EXISTS V_RETAIL_CPO_SALES_MTD_BY_MARKET
;
DROP VIEW IF EXISTS V_RETAIL_CPO_SALES_MTD_BY_REGION
;
DROP VIEW IF EXISTS V_RETAIL_CPO_SALES_MTD_BY_REGION_ZONE
;
DROP VIEW IF EXISTS V_RETAIL_CPO_SALES_MTD_BY_REGION_ZONE_DISTRICT