SELECT DLR_CD, CALENDAR_DATE, TOTAL_GROUND_INVENTORY, WHOLESALE_INTRANSIT, PORT_WATER_NONWHOLESALE_INTRANSIT, PRODUCED_INVENTORY, ON_ORDER
FROM $SCHEMA$FLAT_RETAIL_INVENTORY_BY_DEALER_DATE
WHERE CALENDAR_DATE BETWEEN ? AND ?