SELECT IFNULL(A.DLR_CD, IFNULL(X.DLR_CD_LM, X.DLR_CD_LYM)) AS DLR_CD,
	A.CNT CNT_TM, 
	A.QTY QTY_TM,
	X.CNT_LM, 
	X.QTY_LM, 
	X.CNT_LYM, 
	X.QTY_LYM
FROM
	(SELECT DLR_CD, COUNT(*) CNT, SUM(QTY) QTY
	FROM $SCHEMA$WRK_RETAIL_CPO_SALES_BY_DEALER_DATE
	WHERE TRANSACTION_TYPE = 'CPO' 
	AND   SALES_DATE BETWEEN ? AND ?
	GROUP BY DLR_CD) A
FULL OUTER JOIN
	(
	SELECT B.DLR_CD DLR_CD_LM, B.CNT CNT_LM, B.QTY QTY_LM, 
		C.DLR_CD DLR_CD_LYM, C.CNT CNT_LYM, C.QTY QTY_LYM
	FROM
		(SELECT DLR_CD, COUNT(*) CNT, SUM(QTY) QTY
		FROM $SCHEMA$WRK_RETAIL_CPO_SALES_BY_DEALER_DATE
		WHERE TRANSACTION_TYPE = 'CPO' 
		AND   SALES_DATE BETWEEN ? AND ?
		GROUP BY DLR_CD) B
	FULL OUTER JOIN
		(SELECT DLR_CD, COUNT(*) CNT, SUM(QTY) QTY
		FROM $SCHEMA$WRK_RETAIL_CPO_SALES_BY_DEALER_DATE
		WHERE TRANSACTION_TYPE = 'CPO' 
		AND   SALES_DATE BETWEEN ? AND ?
		GROUP BY DLR_CD) C
	ON B.DLR_CD = C.DLR_CD) X
ON A.DLR_CD = X.DLR_CD_LM
