DROP VIEW IF EXISTS V_RETAIL_INVENTORY_BY_DEALER
;
SELECT IFNULL(A.DLR_CD, IFNULL(X.DLR_CD_LM, X.DLR_CD_LYM)) DLR_CD,
	A.SALES_YYMM SALES_YYMM_TM, 
	A.CNT CNT_TM, 
	A.QTY TQTY_TM, 
	A.SALES_MO_TOTAL_SELL_DAYS TSALE_DAYS_TM,
	A.DSR DSR_TM,
	X.SALES_YYMM_LM,
	X.CNT_LM,
	X.TQTY_LM, 
	X.TSALE_DAYS_LM,
	X.DSR_LM DSR_LM,
	X.SALES_YYMM_LYM,
	X.CNT_LYM,
	X.TQTY_LYM, 
	X.TSALE_DAYS_LYM,
	X.DSR_LYM DSR_LYM
FROM (
	SELECT DLR_CD, 
		SALES_YYMM , 
		CNT, 
		QTY, 
		SALES_MO_TOTAL_SELL_DAYS,
		DSR
	FROM $SCHEMA$WRK_RETAIL_DSR_BY_DEALER 
	WHERE SALES_YYMM = TO_NUMBER(TO_CHAR(TO_DATE(?, 'YYYY-MM-DD'), 'YYYYMM'))
	AND	QTY <> 0
		) A
	FULL OUTER JOIN
	(
	SELECT  B.DLR_CD DLR_CD_LM, 
			B.SALES_YYMM SALES_YYMM_LM, 
			B.CNT CNT_LM, 
			B.QTY TQTY_LM, 
			B.SALES_MO_TOTAL_SELL_DAYS TSALE_DAYS_LM,
			B.DSR DSR_LM,
			C.DLR_CD DLR_CD_LYM, 
			C.SALES_YYMM SALES_YYMM_LYM, 
			C.CNT CNT_LYM, 
			C.QTY TQTY_LYM, 
			C.SALES_MO_TOTAL_SELL_DAYS TSALE_DAYS_LYM,
			C.DSR DSR_LYM
	FROM 
		(
		SELECT DLR_CD, 
			SALES_YYMM , 
			CNT, 
			QTY, 
			SALES_MO_TOTAL_SELL_DAYS,
			DSR
		FROM $SCHEMA$WRK_RETAIL_DSR_BY_DEALER 
		WHERE SALES_YYMM = TO_NUMBER(TO_CHAR(TO_DATE(?, 'YYYY-MM-DD'), 'YYYYMM'))
		AND	QTY <> 0
		) B
	FULL OUTER JOIN
		(
		SELECT DLR_CD, 
			SALES_YYMM , 
			CNT, 
			QTY, 
			SALES_MO_TOTAL_SELL_DAYS,
			DSR
		FROM $SCHEMA$WRK_RETAIL_DSR_BY_DEALER 
		WHERE SALES_YYMM = TO_NUMBER(TO_CHAR(TO_DATE(?, 'YYYY-MM-DD'), 'YYYYMM'))
		AND	QTY <> 0
		) C
	ON B.DLR_CD = C.DLR_CD 
	) X
ON A.DLR_CD = IFNULL(X.DLR_CD_LM, X.DLR_CD_LYM)
