DROP VIEW IF EXISTS $SCHEMA$V_RETAIL_INVENTORY_BY_DEALER
;
CREATE VIEW $SCHEMA$V_RETAIL_INVENTORY_BY_DEALER AS
SELECT
	ID,
	ASON,
	DLR_CD,
	-- TM
	CASEWHEN( C.DSR_TM <> 0,
	ROUND((TOTAL_GROUND_INVENTORY_TM / C.DSR_TM), 0),
	NULL) DEALER_DAYS_OF_SUPPLY_TM,
	--
	CASEWHEN( C.DSR_TM <> 0,
	ROUND((TOTAL_GROUND_INVENTORY_TM +  
	(WHOLESALE_INTRANSIT_TM + 
	PORT_WATER_NONWHOLESALE_INTRANSIT_TM +  
	PRODUCED_INVENTORY_TM) / C.DSR_TM),
	0), NULL) TOTAL_DAYS_OF_SUPPLY_TM,
	--
	CASEWHEN( C.DSR_TM <> 0,
	ROUND((( WHOLESALE_INTRANSIT_TM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_TM) / C.DSR_TM),
	0), NULL) IN_TRANSIT_DAYS_OF_SUPPLY_TM,
	--
	ROUND(C.DSR_TM,2) DAILY_SALES_RATE_TM,
	--
	(TOTAL_GROUND_INVENTORY_TM +  
	WHOLESALE_INTRANSIT_TM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_TM +  
	PRODUCED_INVENTORY_TM) TOTAL_AVAILABLE_TM,
	--
	TOTAL_GROUND_INVENTORY_TM DEALER_STOCK_TM,
	--
	(WHOLESALE_INTRANSIT_TM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_TM) IN_TRANSIT_TM,
	--
	(WHOLESALE_INTRANSIT_TM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_TM +  
	PRODUCED_INVENTORY_TM) INCOMING_INVENTORY_TM,
	--
	(PORT_WATER_NONWHOLESALE_INTRANSIT_TM + PRODUCED_INVENTORY_TM + 
	ON_ORDER_TM) IN_TRANSIT_PRE_WHOLESALE_TM,
	--
	PRODUCED_INVENTORY_TM PRODUCED_TM,
	ON_ORDER_TM,
	C.DSR_TM,
	C.TQTY_TM RETAIL_SALES_TM,
	-- LM
	CASEWHEN( C.DSR_LM <> 0,
	ROUND((TOTAL_GROUND_INVENTORY_LM / C.DSR_LM), 0), NULL) DEALER_DAYS_OF_SUPPLY_LM,
	--
	CASEWHEN( C.DSR_LM <> 0,
	ROUND((TOTAL_GROUND_INVENTORY_LM +  
	(WHOLESALE_INTRANSIT_LM + 
	PORT_WATER_NONWHOLESALE_INTRANSIT_LM +  
	PRODUCED_INVENTORY_LM) / C.DSR_LM), 0), NULL) TOTAL_DAYS_OF_SUPPLY_LM,
	--
	CASEWHEN( C.DSR_LM <> 0,
	ROUND((( WHOLESALE_INTRANSIT_LM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LM) / C.DSR_LM), 0), NULL) IN_TRANSIT_DAYS_OF_SUPPLY_LM,
	--
	ROUND(C.DSR_LM, 2) DAILY_SALES_RATE_LM,
	(TOTAL_GROUND_INVENTORY_LM +  
	WHOLESALE_INTRANSIT_LM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LM +  
	PRODUCED_INVENTORY_LM) TOTAL_AVAILABLE_LM, 
	--
	TOTAL_GROUND_INVENTORY_LM DEALER_STOCK_LM,
	--
	(WHOLESALE_INTRANSIT_LM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LM) IN_TRANSIT_LM,
	--
	(WHOLESALE_INTRANSIT_LM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LM +  
	PRODUCED_INVENTORY_LM) INCOMING_INVENTORY_LM,
	--
	(PORT_WATER_NONWHOLESALE_INTRANSIT_LM + PRODUCED_INVENTORY_LM + 
	ON_ORDER_LM) IN_TRANSIT_PRE_WHOLESALE_LM,
	--
	PRODUCED_INVENTORY_LM PRODUCED_LM,
	ON_ORDER_LM,
	C.DSR_LM,
	C.TQTY_LM RETAIL_SALES_LM,
	-- LYM
	CASEWHEN( C.DSR_LYM <> 0,
	ROUND((TOTAL_GROUND_INVENTORY_LYM / C.DSR_LYM), 0), NULL) DEALER_DAYS_OF_SUPPLY_LYM,
	--
	CASEWHEN( C.DSR_LYM <> 0,
	ROUND((TOTAL_GROUND_INVENTORY_LYM +  
	(WHOLESALE_INTRANSIT_LYM + 
	PORT_WATER_NONWHOLESALE_INTRANSIT_LYM +  
	PRODUCED_INVENTORY_LYM) / C.DSR_LYM), 0), NULL) TOTAL_DAYS_OF_SUPPLY_LYM,
	--
	CASEWHEN( C.DSR_LYM <> 0,
	ROUND((( WHOLESALE_INTRANSIT_LYM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LYM) / C.DSR_LYM), 0), NULL) IN_TRANSIT_DAYS_OF_SUPPLY_LYM,
	--
	ROUND(C.DSR_LYM, 2) DAILY_SALES_RATE_LYM,
	(TOTAL_GROUND_INVENTORY_LYM +  
	WHOLESALE_INTRANSIT_LYM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LYM +  
	PRODUCED_INVENTORY_LYM) TOTAL_AVAILABLE_LYM, 
	TOTAL_GROUND_INVENTORY_LYM DEALER_STOCK_LYM,
	(WHOLESALE_INTRANSIT_LYM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LYM) IN_TRANSIT_LYM,
	(WHOLESALE_INTRANSIT_LYM +  
	PORT_WATER_NONWHOLESALE_INTRANSIT_LYM +  
	PRODUCED_INVENTORY_LYM) INCOMING_INVENTORY_LYM,
	(PORT_WATER_NONWHOLESALE_INTRANSIT_LYM + PRODUCED_INVENTORY_LYM + 
	ON_ORDER_LYM) IN_TRANSIT_PRE_WHOLESALE_LYM,
	PRODUCED_INVENTORY_LYM PRODUCED_LYM,
	ON_ORDER_LYM,
	C.DSR_LYM,
	C.TQTY_LYM RETAIL_SALES_LYM
FROM
	$SCHEMA$RPT_RETAIL_INVENTORY_BY_DEALER A,
	$SCHEMA$RPT_RETAIL_DSR_BY_DEALER C
WHERE
	A.DLR_CD = C.DLR_CD
