SELECT 	DISTINCT A.PRSN_ID_CD, A.STATUS_CD, A.PRSN_TYPE_CD, A.FRST_NM, A.MIDL_NM, A.LAST_NM, B.JOB_CD, B.LOCTN_CD, C.USERID, C.EMAIL_ADDR, 
		' ' RGN_CD, ' ' ZONE_CD, ' ' DISTRICT_CD, D.JOB_TITLE_TX
FROM 	$SCHEMA$BTC03020 A,
		$SCHEMA$BTC03050 B,
		$SCHEMA$BTC03110 C,
		$SCHEMA$BTC03010 D
WHERE   A.PRSN_ID_CD = B.PRSN_ID_CD
AND 	A.PRSN_ID_CD = C.PRSN_ID_CD
AND 	D.JOB_CD = B.JOB_CD
AND 	C.END_DT = '0001-01-01'
AND 	A.LOCTN_CD = ?
