SELECT 	DISTINCT A.PRSN_ID_CD, A.STATUS_CD, A.PRSN_TYPE_CD, A.FRST_NM, A.MIDL_NM, A.LAST_NM, B.JOB_CD, B.LOCTN_CD, C.USERID, C.EMAIL_ADDR, 
		SUBSTR(B.LOCTN_CD, 1, 2)   REGION_CD, ' ' ZONE_CD, ' ' DISTRICT_CD, ' ' TYPE_CD, D.JOB_TITLE_TX    
FROM $SCHEMA$BTC03020 A
LEFT OUTER JOIN $SCHEMA$BTC03050 B 
	ON  A.PRSN_ID_CD = B.PRSN_ID_CD AND 
		A.LOCTN_CD = B.LOCTN_CD AND 
		B.PRIMARY_JOB_FL = 'Y'
LEFT OUTER JOIN $SCHEMA$BTC03010 D 
	ON  B.JOB_CD = D.JOB_CD
LEFT OUTER JOIN 
		(SELECT B311.PRSN_ID_CD, B311.USERID, B311.EMAIL_ADDR
		FROM	$SCHEMA$BTC03110 B311
		WHERE   CASE WHEN B311.END_DT = DATE('0001-01-01') THEN DATE('9999-12-31') ELSE B311.END_DT END = (
				SELECT MAX( CASE WHEN DT.END_DT = DATE('0001-01-01') THEN DATE('9999-12-31') ELSE DT.END_DT END )
				FROM  $SCHEMA$BTC03110 DT
				WHERE B311.PRSN_ID_CD = DT.PRSN_ID_CD )
		) C 
	ON A.PRSN_ID_CD = C.PRSN_ID_CD
