SELECT E.PRSN_ID_CD, E.STATUS_CD, E.PRSN_TYPE_CD, E.FRST_NM, E.MIDL_NM, E.LAST_NM,
		STR1_AD, E.STR2_AD, E.STR3_AD, E.CITY_AD, E.ST_CD, E.ZIP_CD, E.CNTRY_CD, E.HIRE_CD,
		HIRE_DT, E.TRMNTN_DT, E.LOCTN_CD, E.JOB_START_DT, E.JOB_CD, E.JOB_TITLE_TX,
		JOB_TYPE_CD, E.W_UPDT_DT 
FROM $SCHEMA$EMPLOYEES E,
	 $SCHEMA$DEALERS D
WHERE E.LOCTN_CD = D.DLR_CD
AND   D.STATUS_CD = 'A'
AND   E.STATUS_CD = 'A'
{AND DEALERS:d}
