SELECT 
	X.DBA_NM,
	X.STATUS_CD,
	X.STATUS_DT,
	X.RGN_CD,
	X.CITY_NM,
	X.ZIP1_CD,
	X.CNTY_CD,
	X.ST_CD,
	X.MDA_CD,
	X.SOA_NM,
	X.APPT_DT,
	X.TERM_DT,
	X.PREV_DLR_CD,
	X.NXT_DLR_CD,
	X.TIME_ZONE_CD,
	X.SOA_CD,
	X.USED_CAR_FL,
	X.CNTRY_CD,
	X.ZIP2_CD,
	X.DLR_INACTV_DT,
	X.SVC_ONLY_FL,
	X.SVC_ONLY_DT,
	X.ZONE_CD,
	X.DISTRICT_CD,
	X.FACILITY_TYPE,
	X.DLR_CD
FROM (	SELECT
		A.APPT_DT APPT_DT,
		A.CITY_NM CITY_NM,
		A.CNTRY_CD CNTRY_CD,
		A.CNTY_CD CNTY_CD,
		A.DBA_NM DBA_NM,
		B.DSTRCT_CD DISTRICT_CD,
		A.DLR_CD DLR_CD,
		A.DLR_INACTV_DT DLR_INACTV_DT,
		A.FCLTY_TYPE_CD FACILITY_TYPE,
		A.MDA_CD MDA_CD,
		A.NXT_DLR_CD NXT_DLR_CD,
		A.PREV_DLR_CD PREV_DLR_CD,
		B.RGN_CD RGN_CD,
		A.SOA_CD SOA_CD,
		A.SOA_NM SOA_NM,
		A.ST_CD ST_CD,
		A.STATUS_CD STATUS_CD,
		A.STATUS_DT STATUS_DT,
		A.SVC_ONLY_DT SVC_ONLY_DT,
		A.SVC_ONLY_FL SVC_ONLY_FL,
		A.TERM_DT TERM_DT,
		A.TIME_ZONE_CD TIME_ZONE_CD,
		A.USED_CAR_FL USED_CAR_FL,
		A.LAST_UPDT_TM W_UPDT_DT,
		A.ZIP1_CD ZIP1_CD,
		A.ZIP2_CD ZIP2_CD,
		B.ZONE_CD ZONE_CD,
		C.RGN_NM RGN_NM
	FROM
		$SCHEMA$BTC02010 A ,
		$SCHEMA$BTC02090 B,
		$SCHEMA$BTC02200 C
	WHERE
		A.DLR_CD = B.DLR_CD
	AND
		B.TYPE_CD = 'V'
	AND 
		B.EFF_END_DT = '0001-01-01'
	AND
		B.RGN_CD IN ('GU', 'MW', 'NE', 'PA')
	AND
		B.DSTRCT_CD   <> '99'
	AND
		B.ZONE_CD  <> '99'
	AND
		C.RGN_CD = B.RGN_CD 
	AND
		A.STATUS_CD  = 'A'
	AND 
		( (A.DLR_CD LIKE ?) OR (A.DBA_NM LIKE ?) )) X
{WHERE DEALERS:X}