SELECT 	DISTINCT A.PRSN_ID_CD, A.STATUS_CD, A.PRSN_TYPE_CD, A.FRST_NM, A.MIDL_NM, A.LAST_NM, ' ' JOB_CD, A.LOCTN_CD, ' ' USERID, ' ' EMAIL_ADDR, 
		' ' RGN_CD, ' ' ZONE_CD, ' ' DISTRICT_CD, ' ' TYPE_CD, ' ' JOB_TITLE_TX
		FROM 	$SCHEMA$BTC03020 A
		WHERE   PRSN_TYPE_CD = 'D'
		AND 	A.LOCTN_CD = ?
		AND 	(CASE WHEN A.TRMNTN_DT = DATE('0001-01-01') THEN DATE('9999-12-31') ELSE A.TRMNTN_DT END) > ? 
ORDER BY 1