SELECT
	A.ID,
	A.ASON,
	A.DLR_CD,
	B.DBA_NM,
	B.RGN_CD,
	IFNULL(CNT_TM,0) CNT_TM,
	IFNULL(QTY_TM,0) QTY_TM,
	IFNULL(CNT_LM,0) CNT_LM,
	IFNULL(QTY_LM,0) QTY_LM,
	IFNULL(CNT_LYM,0) CNT_LYM,
	IFNULL(QTY_LYM,0) QTY_LYM
FROM
	$SCHEMA$RPT_RETAIL_SALES_BY_DEALER A,
	$SCHEMA$DEALERS B
WHERE
	ASON = ?
AND	A.DLR_CD = B.DLR_CD
{AND DEALERS:B}
