SELECT  RGN_CD, DSTRCT_CD, count(*) 
FROM (SELECT RGN_CD, TYPE_CD, ZONE_CD, DSTRCT_CD, to_char(EFF_END_DT, 'YYYY-MM-DD')
		FROM MMAS.BTC02090 
		WHERE TYPE_CD = 'V'
		AND to_char(EFF_END_DT, 'YYYY-MM-DD') = '0001-01-01'
		 ) X
GROUP BY RGN_CD, DSTRCT_CD
HAVING COUNT(*) > 1



SELECT  DISTINCT RGN_CD, TYPE_CD, ZONE_CD, DSTRCT_CD, to_char(EFF_END_DT, 'YYYY-MM-DD')
		FROM MMAS.BTC02090 
		WHERE TYPE_CD = 'V'
		AND to_char(EFF_END_DT, 'YYYY-MM-DD') = '0001-01-01'
		AND RGN_CD = 'GU'
ORDER BY 1