logging:
  level:
    root: DEBUG

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /manage
      exposure.include: mappings,health
    mappings:
      enabled: true

app:
  appName: Contact Report
  name: Contact Report