SELECT  TABLE_NAME, 
		EDW_VIEW_NAME, 
		LAST_UPDATE_DATE
FROM $SCHEMA$LAST_EDW_UPDATE_DATES
;
DROP INDEX IF EXISTS $SCHEMA$IX_LAST_EDW_UPDATE_DATES
;
CREATE INDEX $SCHEMA$IX_LAST_EDW_UPDATE_DATES ON $SCHEMA$LAST_EDW_UPDATE_DATES(TABLE_NAME)
