DROP VIEW IF EXISTS V_RETAIL_INVENTORY_BY_DEALER
;
SELECT IFNULL(A.DLR_CD, IFNULL(X.DLR_CD_LM, X.DLR_CD_LYM)) DLR_CD,
	A.EFF_YYMM EFF_YYMM_TM,
	A.CNT CNT_TM, 
	A.TOTAL_GROUND_INVENTORY TOTAL_GROUND_INVENTORY_TM,
	A.WHOLESALE_INTRANSIT WHOLESALE_INTRANSIT_TM, 
	A.PORT_WATER_NONWHOLESALE_INTRANSIT PORT_WATER_NONWHOLESALE_INTRANSIT_TM, 
	A.PRODUCED_INVENTORY PRODUCED_INVENTORY_TM, 
	A.ON_ORDER ON_ORDER_TM, 
	X.EFF_YYMM_LM,
	X.CNT_LM, 
	X.TOTAL_GROUND_INVENTORY_LM,
	X.WHOLESALE_INTRANSIT_LM, 
	X.PORT_WATER_NONWHOLESALE_INTRANSIT_LM, 
	X.PRODUCED_INVENTORY_LM, 
	X.ON_ORDER_LM, 
	X.EFF_YYMM_LYM,
	X.CNT_LYM, 
	X.TOTAL_GROUND_INVENTORY_LYM,
	X.WHOLESALE_INTRANSIT_LYM, 
	X.PORT_WATER_NONWHOLESALE_INTRANSIT_LYM, 
	X.PRODUCED_INVENTORY_LYM, 
	X.ON_ORDER_LYM 
FROM
	(SELECT DLR_CD,  
			TO_NUMBER(TO_CHAR(MAX(CALENDAR_DATE), 'YYYYMM')) EFF_YYMM, 
			COUNT(*) CNT, 
			SUM(IFNULL(TOTAL_GROUND_INVENTORY,0 )) TOTAL_GROUND_INVENTORY, 
			SUM(IFNULL(WHOLESALE_INTRANSIT,0 )) WHOLESALE_INTRANSIT, 
			SUM(IFNULL(PORT_WATER_NONWHOLESALE_INTRANSIT,0 )) PORT_WATER_NONWHOLESALE_INTRANSIT, 
			SUM(IFNULL(PRODUCED_INVENTORY,0 ))PRODUCED_INVENTORY, 
			SUM(IFNULL(ON_ORDER,0 )) ON_ORDER
		FROM $SCHEMA$WRK_RETAIL_INVENTORY_BY_DEALER_DATE
		WHERE CALENDAR_DATE BETWEEN ? AND ?
		GROUP BY DLR_CD) A
FULL OUTER JOIN
	(
	SELECT B.DLR_CD DLR_CD_LM, 
	B.EFF_YYMM EFF_YYMM_LM,
	B.CNT CNT_LM, 
	B.TOTAL_GROUND_INVENTORY TOTAL_GROUND_INVENTORY_LM,
	B.WHOLESALE_INTRANSIT WHOLESALE_INTRANSIT_LM, 
	B.PORT_WATER_NONWHOLESALE_INTRANSIT PORT_WATER_NONWHOLESALE_INTRANSIT_LM, 
	B.PRODUCED_INVENTORY PRODUCED_INVENTORY_LM, 
	B.ON_ORDER ON_ORDER_LM, 
	C.DLR_CD DLR_CD_LYM, 
	B.EFF_YYMM EFF_YYMM_LYM,
	C.CNT CNT_LYM, 
	C.TOTAL_GROUND_INVENTORY TOTAL_GROUND_INVENTORY_LYM,
	C.WHOLESALE_INTRANSIT WHOLESALE_INTRANSIT_LYM, 
	C.PORT_WATER_NONWHOLESALE_INTRANSIT PORT_WATER_NONWHOLESALE_INTRANSIT_LYM, 
	C.PRODUCED_INVENTORY PRODUCED_INVENTORY_LYM, 
	C.ON_ORDER ON_ORDER_LYM 
	FROM
		(SELECT DLR_CD, 
			TO_NUMBER(TO_CHAR(MAX(CALENDAR_DATE), 'YYYYMM')) EFF_YYMM, 
			COUNT(*) CNT,
			SUM(IFNULL(TOTAL_GROUND_INVENTORY,0 )) TOTAL_GROUND_INVENTORY, 
			SUM(IFNULL(WHOLESALE_INTRANSIT,0 )) WHOLESALE_INTRANSIT, 
			SUM(IFNULL(PORT_WATER_NONWHOLESALE_INTRANSIT,0 )) PORT_WATER_NONWHOLESALE_INTRANSIT, 
			SUM(IFNULL(PRODUCED_INVENTORY,0 ))PRODUCED_INVENTORY, 
			SUM(IFNULL(ON_ORDER,0 )) ON_ORDER
		FROM $SCHEMA$WRK_RETAIL_INVENTORY_BY_DEALER_DATE
		WHERE CALENDAR_DATE BETWEEN ? AND ?
		GROUP BY DLR_CD) B
	FULL OUTER JOIN
		(SELECT DLR_CD, 
			TO_NUMBER(TO_CHAR(MAX(CALENDAR_DATE), 'YYYYMM')) EFF_YYMM, 
			COUNT(*) CNT,
			SUM(IFNULL(TOTAL_GROUND_INVENTORY,0 )) TOTAL_GROUND_INVENTORY, 
			SUM(IFNULL(WHOLESALE_INTRANSIT,0 )) WHOLESALE_INTRANSIT, 
			SUM(IFNULL(PORT_WATER_NONWHOLESALE_INTRANSIT,0 )) PORT_WATER_NONWHOLESALE_INTRANSIT, 
			SUM(IFNULL(PRODUCED_INVENTORY,0 ))PRODUCED_INVENTORY, 
			SUM(IFNULL(ON_ORDER,0 )) ON_ORDER
		FROM $SCHEMA$WRK_RETAIL_INVENTORY_BY_DEALER_DATE
		WHERE CALENDAR_DATE BETWEEN ? AND ?
		GROUP BY DLR_CD) C
	ON B.DLR_CD = C.DLR_CD) X
ON A.DLR_CD = X.DLR_CD_LM
