SELECT
	? PERIOD,
	INV_YYMM,
	B.SALES_MO_CLOSE_DAY,
	ROUND((TOTAL_GROUND_INVENTORY / DSR),0) DEALER_DAYS_OF_SUPPLY,
	ROUND((TOTAL_GROUND_INVENTORY +  
	(WHOLESALE_INTRANSIT + 
	PORT_WATER_NONWHOLESALE_INTRANSIT +  
	PRODUCED_INVENTORY) / DSR),0) TOTAL_DAYS_OF_SUPPLY,
	ROUND((( WHOLESALE_INTRANSIT +  
	PORT_WATER_NONWHOLESALE_INTRANSIT) / DSR),0) IN_TRANSIT_DAYS_OF_SUPPLY,
	ROUND(DSR,2) DAILY_SALES_RATE,
	(TOTAL_GROUND_INVENTORY +  
	WHOLESALE_INTRANSIT +  
	PORT_WATER_NONWHOLESALE_INTRANSIT +  
	PRODUCED_INVENTORY) TOTAL_AVAILABLE, 
	TOTAL_GROUND_INVENTORY DEALER_STOCK,
	(WHOLESALE_INTRANSIT +  
	PORT_WATER_NONWHOLESALE_INTRANSIT) IN_TRANSIT,
	(WHOLESALE_INTRANSIT +  
	PORT_WATER_NONWHOLESALE_INTRANSIT +  
	PRODUCED_INVENTORY) INCOMING_INVENTORY,
	(PORT_WATER_NONWHOLESALE_INTRANSIT + PRODUCED_INVENTORY + 
	ON_ORDER) IN_TRANSIT_PRE_WHOLESALE,
	PRODUCED_INVENTORY PRODUCED,
	ON_ORDER,
	QTY RETAIL_SALES
FROM (
	SELECT
		INV_YYMM,
		SUM(IFNULL(TOTAL_GROUND_INVENTORY,0)) TOTAL_GROUND_INVENTORY,
		SUM(IFNULL(WHOLESALE_INTRANSIT,0)) WHOLESALE_INTRANSIT,
		SUM(IFNULL(PORT_WATER_NONWHOLESALE_INTRANSIT,0)) PORT_WATER_NONWHOLESALE_INTRANSIT,
		SUM(IFNULL(PRODUCED_INVENTORY,0)) PRODUCED_INVENTORY,
		SUM(IFNULL(ON_ORDER,0)) ON_ORDER,
		SUM(QTY) QTY,
		SUM(DSR) DSR
	FROM
		$SCHEMA$RETAIL_INVENTORY_BY_DEALER_MTD X
	WHERE
		INV_YYMM >= TO_NUMBER(TO_CHAR(ADD_MONTHS(TO_DATE (?, 'YYYY-MM-DD'), -13), 'YYYYMM'))
	AND	ASON = ?
	{AND DEALERS:X} 
	GROUP BY INV_YYMM ) A,
	(SELECT DISTINCT 
		SALES_YR_MO_ID, 
		SALES_MO_CLOSE_DAY 
	FROM $SCHEMA$DATEMASTER) B
WHERE A.INV_YYMM = B.SALES_YR_MO_ID	