package com.mnao.mfp.pdf.util;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

import com.mnao.mfp.cr.entity.ContactReportInfo;
import com.mnao.mfp.cr.entity.Dealers;

@Component
public class PdfGenerateUtil {
	
	private final String HTML = "<html>\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta http-equiv=Content-Type content=\"text/html; charset=UTF-8\">\r\n"
			+ "    <style type=\"text/css\">\r\n"
			+ "        \r\n"
			+ "      table,\r\n"
			+ "      tr,\r\n"
			+ "      td,\r\n"
			+ "      th,tbody {\r\n"
			+ "        border: 1px solid black;\r\n"
			+ "        font-size: 15px;\r\n"
			+ "        text-align: left;\r\n"
			+ "        margin-left: auto;\r\n"
			+ "        margin-right: auto;\r\n"
			+ "        width: 550px;\r\n"
			+ "      }\r\n"
			+ "\r\n"
			+ "\r\n"
			+ ":root {\r\n"
			+ "	--blue: #007bff;\r\n"
			+ "	--indigo: #6610f2;\r\n"
			+ "	--purple: #6f42c1;\r\n"
			+ "	--pink: #e83e8c;\r\n"
			+ "	--red: #dc3545;\r\n"
			+ "	--orange: #fd7e14;\r\n"
			+ "	--yellow: #ffc107;\r\n"
			+ "	--green: #28a745;\r\n"
			+ "	--teal: #20c997;\r\n"
			+ "	--cyan: #17a2b8;\r\n"
			+ "	--white: #fff;\r\n"
			+ "	--gray: #6c757d;\r\n"
			+ "	--gray-dark: #343a40;\r\n"
			+ "	--primary: #007bff;\r\n"
			+ "	--secondary: #6c757d;\r\n"
			+ "	--success: #28a745;\r\n"
			+ "	--info: #17a2b8;\r\n"
			+ "	--warning: #ffc107;\r\n"
			+ "	--danger: #dc3545;\r\n"
			+ "	--light: #f8f9fa;\r\n"
			+ "	--dark: #343a40;\r\n"
			+ "	--breakpoint-xs: 0;\r\n"
			+ "	--breakpoint-sm: 576px;\r\n"
			+ "	--breakpoint-md: 768px;\r\n"
			+ "	--breakpoint-lg: 992px;\r\n"
			+ "	--breakpoint-xl: 1200px;\r\n"
			+ "	--font-family-sans-serif: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", \"Liberation Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\r\n"
			+ "	--font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "*,\r\n"
			+ "::after,\r\n"
			+ "::before {\r\n"
			+ "	box-sizing: border-box\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "html {\r\n"
			+ "	font-family: sans-serif;\r\n"
			+ "	line-height: 1.15;\r\n"
			+ "	-webkit-text-size-adjust: 100%;\r\n"
			+ "	-webkit-tap-highlight-color: transparent\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "body {\r\n"
			+ "	margin: 0;\r\n"
			+ "	font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", \"Liberation Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\r\n"
			+ "	font-size: 1rem;\r\n"
			+ "	font-weight: 400;\r\n"
			+ "	line-height: 1.5;\r\n"
			+ "	color: #212529;\r\n"
			+ "	text-align: left;\r\n"
			+ "	background-color: #fff\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "[tabindex=\"-1\"]:focus:not(:focus-visible) {\r\n"
			+ "	outline: 0!important\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "h1,\r\n"
			+ "h3,\r\n"
			+ "h5 {\r\n"
			+ "	margin-top: 0;\r\n"
			+ "	margin-bottom: .5rem\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "table {\r\n"
			+ "	border-collapse: collapse\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "button:focus:not(:focus-visible) {\r\n"
			+ "	outline: 0\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "[type=button]:not(:disabled),\r\n"
			+ "[type=reset]:not(:disabled),\r\n"
			+ "[type=submit]:not(:disabled),\r\n"
			+ "button:not(:disabled) {\r\n"
			+ "	cursor: pointer\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "::-webkit-file-upload-button {\r\n"
			+ "	font: inherit;\r\n"
			+ "	-webkit-appearance: button\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "h1,\r\n"
			+ "h3,\r\n"
			+ "h5 {\r\n"
			+ "	margin-bottom: .5rem;\r\n"
			+ "	font-weight: 500;\r\n"
			+ "	line-height: 1.2\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "h1 {\r\n"
			+ "	font-size: 2.5rem\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "h3 {\r\n"
			+ "	font-size: 1.75rem\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "h5 {\r\n"
			+ "	font-size: 1.25rem\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".container {\r\n"
			+ "	width: 100%;\r\n"
			+ "	padding-right: 15px;\r\n"
			+ "	padding-left: 15px;\r\n"
			+ "	margin-right: auto;\r\n"
			+ "	margin-left: auto\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "@media (min-width:576px) {\r\n"
			+ "	.container {\r\n"
			+ "		max-width: 540px\r\n"
			+ "	}\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "@media (min-width:768px) {\r\n"
			+ "	.container {\r\n"
			+ "		max-width: 720px\r\n"
			+ "	}\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "@media (min-width:992px) {\r\n"
			+ "	.container {\r\n"
			+ "		max-width: 960px\r\n"
			+ "	}\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "@media (min-width:1200px) {\r\n"
			+ "	.container {\r\n"
			+ "		max-width: 1140px\r\n"
			+ "	}\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".table {\r\n"
			+ "	width: 100%;\r\n"
			+ "	margin-bottom: 1rem;\r\n"
			+ "	color: #212529\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".table td {\r\n"
			+ "	padding: .75rem;\r\n"
			+ "	vertical-align: top;\r\n"
			+ "	border-top: 1px solid #dee2e6\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".custom-control-input.is-valid:focus:not(:checked)~.custom-control-label::before,\r\n"
			+ ".was-validated .custom-control-input:valid:focus:not(:checked)~.custom-control-label::before {\r\n"
			+ "	border-color: #28a745\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".custom-control-input.is-invalid:focus:not(:checked)~.custom-control-label::before,\r\n"
			+ ".was-validated .custom-control-input:invalid:focus:not(:checked)~.custom-control-label::before {\r\n"
			+ "	border-color: #dc3545\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn:not(:disabled):not(.disabled) {\r\n"
			+ "	cursor: pointer\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-primary:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-primary:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #0062cc;\r\n"
			+ "	border-color: #005cbf\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-primary:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-primary:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(38, 143, 255, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-secondary:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-secondary:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #545b62;\r\n"
			+ "	border-color: #4e555b\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-secondary:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-secondary:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(130, 138, 145, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-success:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-success:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #1e7e34;\r\n"
			+ "	border-color: #1c7430\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-success:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-success:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(72, 180, 97, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-info:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-info:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #117a8b;\r\n"
			+ "	border-color: #10707f\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-info:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-info:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(58, 176, 195, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-warning:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-warning:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #212529;\r\n"
			+ "	background-color: #d39e00;\r\n"
			+ "	border-color: #c69500\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-warning:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-warning:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(222, 170, 12, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-danger:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-danger:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #bd2130;\r\n"
			+ "	border-color: #b21f2d\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-danger:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-danger:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(225, 83, 97, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-light:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-light:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #212529;\r\n"
			+ "	background-color: #dae0e5;\r\n"
			+ "	border-color: #d3d9df\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-light:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-light:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(216, 217, 219, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-dark:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-dark:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #1d2124;\r\n"
			+ "	border-color: #171a1d\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-dark:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-dark:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(82, 88, 93, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-primary:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-primary:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #007bff;\r\n"
			+ "	border-color: #007bff\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-primary:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-primary:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(0, 123, 255, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-secondary:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-secondary:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #6c757d;\r\n"
			+ "	border-color: #6c757d\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-secondary:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-secondary:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(108, 117, 125, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-success:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-success:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #28a745;\r\n"
			+ "	border-color: #28a745\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-success:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-success:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(40, 167, 69, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-info:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-info:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #17a2b8;\r\n"
			+ "	border-color: #17a2b8\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-info:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-info:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(23, 162, 184, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-warning:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-warning:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #212529;\r\n"
			+ "	background-color: #ffc107;\r\n"
			+ "	border-color: #ffc107\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-warning:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-warning:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(255, 193, 7, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-danger:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-danger:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #dc3545;\r\n"
			+ "	border-color: #dc3545\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-danger:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-danger:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(220, 53, 69, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-light:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-light:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #212529;\r\n"
			+ "	background-color: #f8f9fa;\r\n"
			+ "	border-color: #f8f9fa\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-light:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-light:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(248, 249, 250, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-dark:not(:disabled):not(.disabled).active,\r\n"
			+ ".btn-outline-dark:not(:disabled):not(.disabled):active {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #343a40;\r\n"
			+ "	border-color: #343a40\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".btn-outline-dark:not(:disabled):not(.disabled).active:focus,\r\n"
			+ ".btn-outline-dark:not(:disabled):not(.disabled):active:focus {\r\n"
			+ "	box-shadow: 0 0 0 .2rem rgba(52, 58, 64, .5)\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".custom-control-input:focus:not(:checked)~.custom-control-label::before {\r\n"
			+ "	border-color: #80bdff\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".custom-control-input:not(:disabled):active~.custom-control-label::before {\r\n"
			+ "	color: #fff;\r\n"
			+ "	background-color: #b3d7ff;\r\n"
			+ "	border-color: #b3d7ff\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".close:not(:disabled):not(.disabled):focus,\r\n"
			+ ".close:not(:disabled):not(.disabled):hover {\r\n"
			+ "	opacity: .75\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "@supports ((position:-webkit-sticky) or (position:sticky)) {}\r\n"
			+ "\r\n"
			+ "@media print {\r\n"
			+ "	*,\r\n"
			+ "	::after,\r\n"
			+ "	::before {\r\n"
			+ "		text-shadow: none!important;\r\n"
			+ "		box-shadow: none!important\r\n"
			+ "	}\r\n"
			+ "	tr {\r\n"
			+ "		page-break-inside: avoid\r\n"
			+ "	}\r\n"
			+ "	h3 {\r\n"
			+ "		orphans: 3;\r\n"
			+ "		widows: 3\r\n"
			+ "	}\r\n"
			+ "	h3 {\r\n"
			+ "		page-break-after: avoid\r\n"
			+ "	}\r\n"
			+ "	@page {\r\n"
			+ "		size: a3\r\n"
			+ "	}\r\n"
			+ "	body {\r\n"
			+ "		min-width: 992px!important\r\n"
			+ "	}\r\n"
			+ "	.container {\r\n"
			+ "		min-width: 992px!important\r\n"
			+ "	}\r\n"
			+ "	.table {\r\n"
			+ "		border-collapse: collapse!important\r\n"
			+ "	}\r\n"
			+ "	.table td {\r\n"
			+ "		background-color: #fff!important\r\n"
			+ "	}\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "    </style>\r\n"
			+ "   \r\n"
			+ "  \r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <!-- section 1 -->\r\n"
			+ "    <div >\r\n"
			+ "\r\n"
			+ "        <div class=\"container\">\r\n"
			+ "            <h3 style=\"text-align: center;\">Contact Report</h3>     \r\n"
			+ "            <table class=\"table\">\r\n"
			+ "                <h5>1. Dealership Details</h5>\r\n"
			+ "              <tbody>\r\n"
			+ "                <tr>\r\n"
			+ "                  <td colspan=\"3\"><div style=\"font-weight: 600;\">DEALERSHIP NAME :</div>\r\n"
			+ "                      %DEALER_NAME% - %DEALER_CODE%</td>\r\n"
			+ "                  <td rowspan=\"3\" style=\"text-align: center; padding-top: 7%;\"><h1>STATUS : 4</h1></td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr>\r\n"
			+ "                    <td colspan=\"3\"><div style=\"font-weight: 600;\">REVIEWER :</div>\r\n"
			+ "                        **************\r\n"
			+ "                    </td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr>\r\n"
			+ "                    <td colspan=\"3\"><div style=\"font-weight: 600;\">AUTHOR : (Name,Title)</div>\r\n"
			+ "                        Nisha Budhiraja</td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr>\r\n"
			+ "                  <td>\r\n"
			+ "                    <div style=\"font-weight: 600;\"> ADDRESS :</div>\r\n"
			+ "                      BROOKFIELD, WI 53045\r\n"
			+ "                  </td>\r\n"
			+ "                  <td>\r\n"
			+ "                    <div style=\"font-weight: 600;\">  PHONE :</div>\r\n"
			+ "                      **********\r\n"
			+ "                  </td>\r\n"
			+ "                  <td>Page 1 of 16</td>\r\n"
			+ "                  <td>\r\n"
			+ "                    <div style=\"font-weight: 600;\"> CONTACT DATE :</div>\r\n"
			+ "                    03-31-2022<br>\r\n"
			+ "                    (Month, Day, year)\r\n"
			+ "                </td>\r\n"
			+ "                </tr>\r\n"
			+ "              </tbody>\r\n"
			+ "            </table>\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "            <table class=\"table\">\r\n"
			+ "                <h5>2. Personnel</h5>\r\n"
			+ "                <tbody>\r\n"
			+ "                  <tr>\r\n"
			+ "                    <td style=\"font-weight: 600;\">AUTHOR :</td>\r\n"
			+ "                        <td> Nisha Budhiraja</td>\r\n"
			+ "                  </tr>\r\n"
			+ "                  <tr>\r\n"
			+ "                    <td style=\"font-weight: 600;\">REVIEWER :</td>\r\n"
			+ "                    <td> M00315563</td>\r\n"
			+ "                  </tr>\r\n"
			+ "                  <tr>\r\n"
			+ "                     <td style=\"font-weight: 600;\">DEALERSHIP CONTACTS :</td>\r\n"
			+ "                     <td>SHAWN DONNELLY</td>   \r\n"
			+ "                  </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "\r\n"
			+ "            </table>\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "                <table class=\"table\">\r\n"
			+ "                    <h5>3. Discussion</h5>\r\n"
			+ "                    <tbody>\r\n"
			+ "                      <tr>\r\n"
			+ "                        <td style=\"font-weight: 600;\">DISCUSSION TYPE :</td>\r\n"
			+ "                        <td style=\"font-weight: 600;\">STATUS :</td>\r\n"
			+ "                        <td style=\"font-weight: 600;\">DATE :</td>\r\n"
			+ "                      </tr>\r\n"
			+ "                      <tr>\r\n"
			+ "                        <td>Co-op Sales</td>\r\n"
			+ "                        <td>Testing 1</td>\r\n"
			+ "                        <td>10/04/22</td>\r\n"
			+ "                      </tr>\r\n"
			+ "\r\n"
			+ "                    </tbody>\r\n"
			+ "                  </table>\r\n"
			+ "            </div>\r\n"
			+ "<!-- section5 -->\r\n"
			+ "        <div class=\"container\">\r\n"
			+ "       <h5 >4. Verification</h5>\r\n"
			+ "       <div >I have read and understand FPPC Regulation 18702.5. I have verified that the appointment and information identified above is true to the best of my information and belief.</div>\r\n"
			+ "       <table class=\"table\">\r\n"
			+ "        <tbody>\r\n"
			+ "          <tr>\r\n"
			+ "            <td style=\"font-weight: 600;\">SIGNATURE OF AGENCY HEAD OR DESIGNEE</td>\r\n"
			+ "            <td style=\"font-weight: 600;\">PRINT NAME</td>\r\n"
			+ "            <td style=\"font-weight: 600;\">TITLE</td>\r\n"
			+ "            <td style=\"font-weight: 600;\">DATE</td>\r\n"
			+ "          </tr>\r\n"
			+ "          <tr style=\"height: 50px;\">\r\n"
			+ "              <td></td>\r\n"
			+ "              <td></td>\r\n"
			+ "              <td></td> \r\n"
			+ "              <td></td>\r\n"
			+ "          </tr>\r\n"
			+ "\r\n"
			+ "        </tbody>\r\n"
			+ "      </table><br>\r\n"
			+ "      <div><span>Comment :</span>&nbsp; &nbsp;__________________________________________________________________________________________________________________________________</div>\r\n"
			+ "      <div style=\"text-align: right;\">FPPC Form 806 (1/18)</div>\r\n"
			+ "      <div style=\"text-align: right;\">FPPC Toll-Free Helpline: 866/ASK-FPPC (866/275-3772)</div>\r\n"
			+ "    </div>\r\n"
			+ "    </div>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>";
	
	public List<String> replaceStringWithData(List<ContactReportInfo> contactReports) {
		List<String> fullHtml = new ArrayList<>();
		contactReports.forEach(cr -> {
			Dealers dealers = cr.getDealers();
			String updatedHtml = HTML.replace("%DEALER_NAME%", dealers.getDbaNm()).replace("%DEALER_CODE%", dealers.getDlrCd());
			fullHtml.add(updatedHtml);
		});
		return fullHtml;
	}

}
