MERGE INTO  $SCHEMA$DEALERS AS DLR 
USING (SELECT
	DLR_CD,
	DBA_NM,
	STATUS_CD,
	STATUS_DT,
	RGN_CD,
	CITY_NM,
	ZIP1_CD,
	CNTY_CD,
	ST_CD,
	MDA_CD,
	SOA_NM,
	APPT_DT,
	TERM_DT,
	PREV_DLR_CD,
	NXT_DLR_CD,
	TIME_ZONE_CD,
	SOA_CD,
	USED_CAR_FL,
	CNTRY_CD,
	ZIP2_CD,
	DLR_INACTV_DT,
	SVC_ONLY_FL,
	SVC_ONLY_DT,
	MDA_NM,
	LAT,
	LON,
	ZONE_CD,
	DISTRICT_CD,
	DEALERSTRTEND,
	DEALEREFFEND,
	FACILITY_TYPE,
	SHOWROOM_TYPE,
	RGN_NM,
	DEALERSHIP_FLAG,
	W_UPDT_DT
FROM
	$SCHEMA$DEALERS_STAGE A
WHERE
	A.RGN_CD IN ('GU', 'MW', 'NE', 'PA')
	AND
	A.DISTRICT_CD <> '99'
	AND
	A.ZONE_CD <> '99'
	AND
	TO_DATE(COALESCE(A.DEALEREFFEND, '31-DEC-2099'), 'DD-MON-YYYY') = (
	SELECT
		MAX(TO_DATE(COALESCE(B.DEALEREFFEND, '31-DEC-2099'), 'DD-MON-YYYY'))
	FROM
		$SCHEMA$DEALERS_STAGE B
	WHERE
		B.DLR_CD = A.DLR_CD)
	) AS STG
	ON (DLR.DLR_CD = STG.DLR_CD)
WHEN MATCHED THEN 
	UPDATE SET 
		DLR.RGN_CD  = STG.RGN_CD,
		DLR.RGN_NM  = STG.RGN_NM,
		DLR.ZONE_CD  = STG.ZONE_CD,
		DLR.DISTRICT_CD = STG.DISTRICT_CD,
		DLR.W_UPDT_DT = STG.W_UPDT_DT
WHEN NOT MATCHED THEN 
	INSERT 
		(	
		DLR_CD,
		DBA_NM,
		STATUS_CD,
		STATUS_DT,
		RGN_CD,
		CITY_NM,
		ZIP1_CD,
		CNTY_CD,
		ST_CD,
		MDA_CD,
		SOA_NM,
		APPT_DT,
		TERM_DT,
		PREV_DLR_CD,
		NXT_DLR_CD,
		TIME_ZONE_CD,
		SOA_CD,
		USED_CAR_FL,
		CNTRY_CD,
		ZIP2_CD,
		DLR_INACTV_DT,
		SVC_ONLY_FL,
		SVC_ONLY_DT,
		MDA_NM,
		LAT,
		LON,
		ZONE_CD,
		DISTRICT_CD,
		DEALERSTRTEND,
		DEALEREFFEND,
		FACILITY_TYPE,
		SHOWROOM_TYPE,
		RGN_NM,
		DEALERSHIP_FLAG,
		W_UPDT_DT
		)
	VALUES (
		STG.DLR_CD,
		STG.DBA_NM,
		STG.STATUS_CD,
		STG.STATUS_DT,
		STG.RGN_CD,
		STG.CITY_NM,
		STG.ZIP1_CD,
		STG.CNTY_CD,
		STG.ST_CD,
		STG.MDA_CD,
		STG.SOA_NM,
		STG.APPT_DT,
		STG.TERM_DT,
		STG.PREV_DLR_CD,
		STG.NXT_DLR_CD,
		STG.TIME_ZONE_CD,
		STG.SOA_CD,
		STG.USED_CAR_FL,
		STG.CNTRY_CD,
		STG.ZIP2_CD,
		STG.DLR_INACTV_DT,
		STG.SVC_ONLY_FL,
		STG.SVC_ONLY_DT,
		STG.MDA_NM,
		STG.LAT,
		STG.LON,
		STG.ZONE_CD,
		STG.DISTRICT_CD,
		STG.DEALERSTRTEND,
		STG.DEALEREFFEND,
		STG.FACILITY_TYPE,
		STG.SHOWROOM_TYPE,
		STG.RGN_NM,
		STG.DEALERSHIP_FLAG,
		STG.W_UPDT_DT) 

	