SELECT  
	A.APPT_DT APPT_DT,
	A.CITY_NM CITY_NM,
	A.CNTRY_CD CNTRY_CD,
	A.CNTY_CD CNTY_CD,
	A.DBA_NM DBA_NM,
	B.DSTRCT_CD DISTRICT_CD,
	A.DLR_CD DLR_CD,
	A.DLR_INACTV_DT DLR_INACTV_DT,
	A.FCLTY_TYPE_CD FACILITY_TYPE,
	A.MDA_CD MDA_CD,
	A.NXT_DLR_CD NXT_DLR_CD,
	A.PREV_DLR_CD PREV_DLR_CD,
	(CASE WHEN B.RGN_CD = 'SE' THEN 'GU' ELSE B.RGN_CD END) RGN_CD,
	A.SOA_CD SOA_CD,
	A.SOA_NM SOA_NM,
	A.ST_CD ST_CD,
	A.STATUS_CD STATUS_CD,
	A.STATUS_DT STATUS_DT,
	A.SVC_ONLY_DT SVC_ONLY_DT,
	A.SVC_ONLY_FL SVC_ONLY_FL,
	A.TERM_DT TERM_DT,
	A.TIME_ZONE_CD TIME_ZONE_CD,
	A.USED_CAR_FL USED_CAR_FL,
	A.LAST_UPDT_TM W_UPDT_DT,
	A.ZIP1_CD ZIP1_CD,
	A.ZIP2_CD ZIP2_CD,
	B.ZONE_CD ZONE_CD,
	C.RGN_NM RGN_NM
FROM
	$SCHEMA$BTC02010 A ,
	$SCHEMA$BTC02090 B ,
	$SCHEMA$BTC02200 C
WHERE
	A.DLR_CD = B.DLR_CD
AND
	B.TYPE_CD = 'V'
AND 
	CASE WHEN B.EFF_END_DT = DATE('0001-01-01') THEN DATE('9999-12-31') ELSE B.EFF_END_DT END = (
	SELECT MAX( CASE WHEN D.EFF_END_DT = DATE('0001-01-01') THEN DATE('9999-12-31') ELSE D.EFF_END_DT END )
	FROM  $SCHEMA$BTC02090 D
	WHERE  A.DLR_CD = D.DLR_CD 
	)
AND
	B.RGN_CD IN ('GU', 'MW', 'NE', 'PA', 'SE')
AND
	B.DSTRCT_CD   <> '99'
AND
	B.ZONE_CD  <> '99' 
AND
	C.RGN_CD = B.RGN_CD 
AND 
	A.LAST_UPDT_TM > ?
